# Generated by Django 5.2.14 on 2026-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
