# Generated by Django 5.2.14 on 2026-06-03 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido')], default='ATIVO', max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_emprestimos', to='acervo.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='usuarios.usuario')),
            ],
        ),
    ]
